### ISSUE TITLE
Use JsonProperty if VariableName is 'protected', 'private', 'public', 'static'

### ISSUE THREAD

**Issue by NoNamePro0** [Json2CSharp/Json2CSharpCodeGenerator#8]
Hey 👋

if on the JSON is a Variable Name is like 'protected', 'private', 'public', 'static',... then it takes on C# a error.

I would implement, if it's like these Names, it use JsonProperty and make Pascal Case.

**Comment by Json2CSharp** [comment]
These keywords can be prepended with @ in order to escape them and the tool should add the attributes as well, i know about this issue but havn't got the time to look into it. will make the project open source and add a test for this as well, documentation might be up in two weeks or so
Thanks for the heads up !

**Comment by NoNamePro0** [comment]
Oh, perfect. If it's come open soure, I will read the code and hope I can contribute more. I love this Project

**Comment by tyeth** [comment]
Fixed by #14

**Comment by NoNamePro0** [comment]
Oh nice!
